.npmignore
=> add folders to .npmignore

contracts/BootstrapRewards.sol, contracts/Committee.sol, contracts/Compliance.sol, contracts/Elections.sol, contracts/Fees.sol, contracts/MonthlySubscriptionPlan.sol, contracts/StakingRewards.sol, contracts/Subscriptions.sol, contracts/ValidatorsRegistration.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/ICommittee.sol, contracts/spec_interfaces/ISubscriptions.sol, test/bootstrap-rewards.spec.ts, test/committee.spec.ts, test/consumer-macros.ts, test/driver.ts, test/elections-compliance.spec.ts, test/elections.spec.ts, test/event-parsing.ts, test/fees.spec.ts, test/helpers.ts, test/matchers.ts, test/staking-rewards.spec.ts, test/subscriptions.spec.ts, typings/committee-contract.d.ts, typings/compliance-contract.d.ts, typings/contracts.ts, typings/elections-contract.d.ts, typings/monthly-subscription-plan-contract.d.ts, typings/subscriptions-contract.d.ts
Integrated with elections contract with e2es.
Based on the previous elections contract (i.e. no linked list at this point).
=> Committee contract

contracts/Protocol.sol, package.json, test/helpers.ts, test/protocol.spec.ts
See https://github.com/orbs-network/orbs-ethereum-contracts/pull/192#discussion_r391179003
=> Allow editing future upgrades

eth.ts, gas-recorder.ts, package.json, test/bootstrap-rewards.spec.ts, test/contract-registry.spec.ts, test/driver.ts, test/elections.spec.ts
Preparing for gas related tests and scenarios
=> Gas recording and reporting

eth.ts
#24 broke compilation when merged into master. fixes this issue
=> fix bad merge of PR #24

eth.ts, gas-recorder.ts, package.json, test/bootstrap-rewards.spec.ts, test/consumer-macros.ts, test/contract-registry.spec.ts, test/driver.ts, test/elections.spec.ts, test/gas-scenarios.spec.ts
=> Gas scenarios

contracts/Protocol.sol, contracts/spec_interfaces/IProtocol.sol, test/protocol.spec.ts, typings/protocol-contract.d.ts
getProtocolVersion() added to `IProtocol`
resolves #35
=> added getProtocolVersion to Protocol contract

contracts/StakingRewards.sol, contracts/spec_interfaces/IStakingRewards.sol, test/event-parsing.ts, test/gas-scenarios.spec.ts, test/matchers.ts, test/staking-rewards.spec.ts, typings/staking-rewards-contract.d.ts
=> Staking rewards events

contracts/Elections.sol
=> remove redundant banning vote check

test/delegations.spec.ts
=> when delegating from one to another, DelegatedStakeChanged for the first should indicate delegation of 0

contracts/spec_interfaces/IStakingRewards.sol
=> index assignee in StakingRewardAssigned event

contracts/StakingRewards.sol
=> prioritize revert messages distributeOrbsTokenRewards - check balance last

test/contract-registry.spec.ts, test/driver.ts, typings/committee-contract.d.ts, typings/contract-registry-contract.d.ts, typings/subscriptions-contract.d.ts
small suggestions for the driver part to make it more helpful
=> Helpers suggestions

contracts/Delegations.sol, contracts/Elections.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/IDelegation.sol, package.json, test/delegations.spec.ts, test/driver.ts, test/elections.spec.ts, test/fees.spec.ts, typings/delegations-contract.d.ts, typings/elections-contract.d.ts, typings/subscriptions-contract.d.ts
resolves #48 
resolves #47
postponing additional interface cleanups and gas optimizations for another PR
=> moved totalGovernanceStake to Elections contract

contracts/Delegations.sol, contracts/Elections.sol, contracts/Erc20AccessorWithTokenGranularity.sol, contracts/Rewards.sol, test/event-parsing.ts, test/fees.spec.ts, test/gas-scenarios.spec.ts, test/staking-rewards.spec.ts
Staking rewards: calculate the annual rate directly, simplifies code and remove remainder logic
Fees: fix flakiness
=> REWARDS: simplify remiander logic, fix flakiness

contracts/Committee.sol, contracts/Elections.sol, contracts/Rewards.sol, contracts/interfaces/IElections.sol, contracts/interfaces/IRewards.sol, test/bootstrap-rewards.spec.ts, test/fees.spec.ts, test/gas-scenarios.spec.ts, test/staking-rewards.spec.ts, typings/elections-contract.d.ts, typings/rewards-contract.d.ts
Save gas by avoiding a call to getCommittee
=> REWARDS: Call assignRewards from committee contract

test/driver.spec.ts, test/driver.ts, typings/contract-registry-contract.d.ts
For staging scenarios need to run a driver with pre-deployed contracts
=> support creating driver with existing contracts

README.md
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a `bug` or resolves a `feature request`, be sure to link to that issue.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Adds npm and license tags to the README

contracts/Elections.sol, contracts/interfaces/IElections.sol, test/elections.spec.ts, test/event-parsing.ts, test/matchers.ts, typings/elections-contract.d.ts
- voteOutTimeoutSeconds
- maxDelegationRatio
- banningLockTimeoutSeconds
- voteOutPercentageThreshold
- banningPercentageThreshold
=> ELECTIONS: getters, setters and events for election contract settings

contracts/Committee.sol, contracts/spec_interfaces/ICommittee.sol, test/committee.spec.ts, typings/committee-contract.d.ts
Adds compliance array to return values of `getCommitteeInfo` and `getStandbysInfo`.
=> COMMITTEE: Add compliance to committee info

contracts/Rewards.sol, contracts/interfaces/IRewards.sol, test/consumer-macros.ts, test/gas-scenarios.spec.ts, test/rewards.spec.ts, typings/rewards-contract.d.ts
- Tracking total balance across all validators for fees, staking and bootstrap rewards. 
- Changing fee distribution bucket limit to 24
fixes #100 
fixes #80
=> REWARDS: Total of balances

contracts/Committee.sol, contracts/spec_interfaces/ICommittee.sol, package.json, test/committee.spec.ts, test/event-parsing.ts, test/matchers.ts, typings/committee-contract.d.ts
- readyToSyncTimeout
- maxCommitteeSize
- maxStandbys
=> COMMITTEE: getters, setters and events for committee settings

contracts/Elections.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/ICommittee.sol, test/committee.spec.ts, test/elections.spec.ts, test/event-parsing.ts, test/matchers.ts, typings/committee-contract.d.ts
`event ValidatorStatusUpdated(address addr, bool readyToSync, bool readyForCommittee);`
=> ELECTIONS: ValidatorStatusUpdated events

contracts/Committee.sol, contracts/Rewards.sol, test/bootstrap-rewards.spec.ts
- Remove reward assignment on config change
- Fix flaky bootstrap rewards test
=> REWARDS: No reward assignment on settings change

.solcover.js, contracts/ContractRegistryAccessor.sol, test/committee.spec.ts, test/contract-registry.spec.ts, test/event-parsing.ts, test/matchers.ts, test/protocol.spec.ts, typings/base-contract.d.ts, typings/committee-contract.d.ts
=> CONTRACT_REGISTRY_ACCESSOR: emit event on address change

contracts/Delegations.sol, test/ganache-driver.ts
- Simplification of the loop
- added some gas price and max gas parameters to GanacheDriver
=> simplify sequence loop

contracts/Delegations.sol, contracts/Elections.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/IDelegation.sol, eth.ts, test/delegations.spec.ts, test/elections.spec.ts, test/gas-scenarios.spec.ts, test/matchers.ts, typings/delegations-contract.d.ts, typings/elections-contract.d.ts
1. Vote out is permenant (remove 1 week grace)
2. Voting limited to 1 vote at a time
=> ELECTIONS: Simplify voteout

test/delegations.spec.ts
=> DELEGATIONS: Missing test - allows delegating to the current delegate

contracts/Delegations.sol, contracts/Elections.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/IElections.sol, test/driver.ts, test/elections.spec.ts, test/event-parsing.ts, test/gas-scenarios.spec.ts, test/matchers.ts, typings/elections-contract.d.ts
=> ELECTIONS: issues

contracts/Delegations.sol, contracts/Elections.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/IElections.sol, test/driver.ts, test/elections.spec.ts, test/event-parsing.ts, test/gas-scenarios.spec.ts, test/matchers.ts, typings/elections-contract.d.ts
=> ELECTIONS: Clear vote-out state

eth.ts, package.json, test/bootstrap-rewards.spec.ts, test/fees.spec.ts, test/helpers.ts, test/staking-rewards.spec.ts, test/subscriptions.spec.ts, top-up-test-accounts.ts
Added retry logic for contract deployment, method calls and getting block
=> TESTKIT: Testnet adjustments

contracts/Elections.sol, contracts/GuardiansRegistration.sol, contracts/Protocol.sol, contracts/ProtocolWallet.sol, contracts/interfaces/IRewards.sol, contracts/spec_interfaces/IProtocolWallet.sol, test/guardian-registration.spec.ts
Fixes of multiple todos + making registration,contact optional.
=> todo fixes + optional contact info

package-lock.json, package.json
After merging #161 publishing a Kovan ready testkit
=> Kovan compliant testkit

contracts/Elections.sol, test/driver.ts, test/elections.spec.ts
=> ELECTIONS: support min self stake == 0

contracts/ContractRegistryAccessor.sol, contracts/Delegations.sol, contracts/StakingContractHandler.sol, contracts/for_testing/GasConsumingStakeChangeNotifier.sol, contracts/for_testing/RevertingStakeChangeNotifier.sol, contracts/spec_interfaces/IDelegation.sol, contracts/spec_interfaces/IStakingContractHandler.sol, test/delegations.spec.ts, test/driver.ts, test/matchers.ts, test/staking-contract-handler.spec.ts, typings/contracts.ts, typings/stake-change-handler-contract.d.ts, typings/staking-contract.d.ts
1. A proxy between the staking contract and the delegations contract that catches reverts and limits gas usage.
2. A wrapper on some staking contract getters
=> Staking Handler

contracts/WithClaimableFunctionalOwnership.sol, contracts/WithClaimableMigrationOwnership.sol, contracts/WithClaimableRegistryManagement.sol
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a `bug` or resolves a `feature request`, be sure to link to that issue.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> pending owner getting, registryAdmin

contracts/Initializable.sol, contracts/Subscriptions.sol, contracts/spec_interfaces/ISubscriptions.sol, test/driver.ts, test/event-parsing.ts, test/subscriptions.spec.ts, typings/subscriptions-contract.d.ts
=> SUBSCRIPTIONS: Initial migration of VCs from previous contract

contracts/Elections.sol, contracts/Rewards.sol, contracts/interfaces/IElections.sol, contracts/spec_interfaces/IElections.sol, test/driver.ts, test/elections-compliance.spec.ts, test/elections.spec.ts, test/event-parsing.ts, test/gas-scenarios.spec.ts, test/matchers.ts, typings/elections-contract.d.ts
voteOut, voteUnready thresholds in percentMille
fixes #169 
fixes #171
=> voteOut, voteUnready percent-mille threshold, #169

contracts/GuardiansRegistration.sol, contracts/WithClaimableFunctionalOwnership.sol, contracts/WithClaimableMigrationOwnership.sol, contracts/WithClaimableRegistryManagement.sol, contracts/spec_interfaces/IGuardiansRegistration.sol, test/driver.ts, test/guardian-registration.spec.ts, typings/guardian-registration-contract.d.ts
=> GUARDIANS_REGISTRY: Remove contact field

contracts/Rewards.sol, contracts/SafeMath48.sol
=> REWARDS: Safemath48 for rewards

contracts/Rewards.sol, contracts/interfaces/IRewards.sol
=> Rewards refactor review1

contracts/Rewards.sol, contracts/spec_interfaces/IRewards.sol, test/driver.ts, test/rewards.spec.ts, typings/rewards-contract.d.ts
Interface file cleanup
activate(..) renamed to activateRewardDistribution(..)
=> Irewards review3

contracts/Subscriptions.sol
=> SUBSCRIPTIONS: Remove unused enum

contracts/StakingRewards.sol, test/rewards.spec.ts
=> STAKING_REWARDS: Skip claiming if total amount is 0

contracts/StakingRewards.sol, contracts/spec_interfaces/IStakingRewards.sol
=> STAKING_REWARDS: Add missing view

contracts/FeesAndBootstrapRewards.sol, contracts/spec_interfaces/IFeesAndBootstrapRewards.sol, test/matchers.ts, test/rewards.spec.ts, typings/fees-and-bootstrap-rewards-contract.d.ts
=> FEES_AND_BOOTSTRAP_REWARDS: Add FeesAllocated and BootstrapRewardsAllocated events

contracts/FeesWallet.sol
=> FEES_WALLET: Use safemath

contracts/FeesAndBootstrapRewards.sol, contracts/FeesWallet.sol, contracts/ProtocolWallet.sol, contracts/StakingRewards.sol, contracts/spec_interfaces/IFeesAndBootstrapRewards.sol, contracts/spec_interfaces/IFeesWallet.sol, contracts/spec_interfaces/IProtocolWallet.sol, contracts/spec_interfaces/IStakingRewards.sol, test/fees-wallet.spec.ts, test/protocol-wallet.spec.ts, test/rewards.spec.ts, typings/fees-and-bootstrap-rewards-contract.d.ts, typings/fees-wallet-contract.d.ts, typings/protocol-wallet-contract.d.ts, typings/staking-rewards-contract.d.ts
=> EmergencyWithdraw - get token as argument

contracts/Committee.sol, contracts/spec_interfaces/ICommittee.sol
=> COMMITTEE: Rename removedMemberEffectiveStake to removedMemberWeight

contracts/Subscriptions.sol, contracts/spec_interfaces/ICertification.sol, contracts/spec_interfaces/ICommittee.sol, contracts/spec_interfaces/IContractRegistry.sol, contracts/spec_interfaces/IContractRegistryListener.sol, contracts/spec_interfaces/IDelegation.sol, contracts/spec_interfaces/IElections.sol, contracts/spec_interfaces/IFeesAndBootstrapRewards.sol, contracts/spec_interfaces/IFeesWallet.sol, contracts/spec_interfaces/IGuardiansRegistration.sol, contracts/spec_interfaces/ILockable.sol, contracts/spec_interfaces/IMigratableFeesWallet.sol, contracts/spec_interfaces/IProtocol.sol, contracts/spec_interfaces/IProtocolWallet.sol, contracts/spec_interfaces/IStakingContractHandler.sol, contracts/spec_interfaces/IStakingRewards.sol, contracts/spec_interfaces/ISubscriptions.sol
Natspec for the interface files
merged with fees_bootstrap_total_awarded PR #302
=> Natspec fixes

contracts/StakingRewards.sol
replaces _getAnnualRate with _getAnnualRewardsPerWeight to increase granularity from 100,000 to 1e18
=> annualRewardsPerWeight improved granularity:

contracts/Delegations.sol, contracts/spec_interfaces/IDelegations.sol, test/delegations.spec.ts, typings/delegations-contract.d.ts
=> DELEGATIONS: Refresh stake batch

contracts/StakingContractHandler.sol
- pack the notify flag along with delegations contract to save a read
- use state for staking contract instead of calling the registry
fixes #324 
fixes #323
=> STAKING_CONTRACT_HANDLER - Gas optimizations
