orbs-network/orbs-ethereum-contracts-v2

eth.ts, package-lock.json, package.json
support `getExisting` in driver for accessing contracts which are already deployed by their address
feature  requested by @talkol
=> Add getExisting (contract) to Driver

contracts/Committee.sol
Avoid the copying of pointers array before sorting it in `computeCommittee`
saves a little gas (~10,000) per invocation
avoid redundant operations.
caution with merging - all call sites of computeCommittee must not assume it preserves the order of the participants array. Currently this is the case
=> computeCommittee does not copy participants before sorting

contracts/Protocol.sol, contracts/spec_interfaces/IProtocol.sol, test/event-parsing.ts, test/helpers.ts, test/protocol.spec.ts, typings/protocol-contract.d.ts
resolves #53
- change protocol version upgrade schedule to be reference time based rather than block number
- add current version to the event
- still not addressing finality concerns because doubt was raised (@vistra) if it's needed.
=> ProtocolVersionChanged - event revised

test/protocol.spec.ts
addressing review comments - avoid flakiness
=> get the timestamp from the appropriate block number without flakiness

contracts/Subscriptions.sol, contracts/spec_interfaces/ISubscriptions.sol, test/driver.ts, test/helpers.ts, test/staking-rewards.spec.ts, test/subscriptions.spec.ts, typings/subscriptions-contract.d.ts
The genesis ref of a new VC is set to a configurable delay from the current time (default 3 hours) as opposed to 300 blocks from the current block.
=> SUBSCRIPTION: Change genesis ref from block number to timestamp

contracts/Rewards.sol, contracts/interfaces/IRewards.sol, test/bootstrap-rewards.spec.ts, test/event-parsing.ts, test/fees.spec.ts, test/matchers.ts, test/staking-rewards.spec.ts, typings/rewards-contract.d.ts
* FeesAssigned and BootstrapRewardAssigned events only report two amounts: certified amount and general amount. THe list of committee members can be obtained by committee events.
* The remainder from fee division is added back to the current bucket instead of assigned to a random member
* New event: FeeWIthdrawnFromBucket, complements FeeAddedToBucket
* Changed stakingRewardsAssigned amounts back to uint256 granularity
=> REWARDS: compact events, better remainder handling

contracts/MonthlySubscriptionPlan.sol, contracts/Rewards.sol, contracts/Subscriptions.sol
Previously the rewards contract trusted to caller to transfer the fees in the specified amount. Now the reward contract is the one making the transfer.
=> SUBSCRIPTIONS/REWARDS: Rewards responsible for all transfers of incoming funds

contracts/Committee.sol, contracts/Compliance.sol, contracts/ContractRegistryAccessor.sol, contracts/Delegations.sol, contracts/Elections.sol, contracts/Lockable.sol, contracts/Protocol.sol, contracts/Rewards.sol, contracts/Subscriptions.sol, contracts/ValidatorsRegistration.sol, test/event-parsing.ts, test/matchers.ts, test/protocol-lockdown.spec.ts, typings/base-contract.d.ts
This allows the migration owner to lock and unlock contract methods. 
- All contract methods which modify the state of the contract are decorated with the -`onlyWhenUnlocked` modifier, which reverts if the contract is in a locked state. 
- The `Lockable` contract (which other contracts inherit from) defines this modifier and the `lock`/`unlock` methods.
=> Contracts Lockdown

contracts/Committee.sol, contracts/ValidatorsRegistration.sol, contracts/spec_interfaces/IValidatorsRegistration.sol, test/elections.spec.ts, test/event-parsing.ts, test/validator-registration.spec.ts, typings/validator-registration-contract.d.ts
- `ValidatorRegistered` event only reports the address
- On registration, we also emit `ValidatorDataUpdated`
=> VALIDATORS_REGISTRATION: modify events

contracts/Rewards.sol, test/staking-rewards.spec.ts
When check the guardion/delegator ratio in staking rewards distribution, allow for an error of up to 1 milli-orbs, to account for rounding errors.
Also, relax the distribution API such that the guardian may or may not appear in the list (instead of enforcing it to always appear first).
=> REWARDS: Easier handling of staking rewards ratio rounding error

contracts/Elections.sol, test/elections.spec.ts, test/fees.spec.ts
Also a bug fix - rejecting readyForX for a banned validator which used its Orbs address.
=> ELECTIONS: readyForX can be sent from Orbs and Guardian addresses

contracts/GuardiansRegistration.sol, eth.ts, test/driver.ts, test/event-parsing.ts, test/guardian-registration.spec.ts
The constructor now takes two arguments - the address of a previous `GuardianRegistration` contract, and a list of addresses to migrate.
It then reads the data into its own state, and also reads a specific metadata field for each guardian - `REWARDS_FREQUENCY_SEC`.
=> GUARDIAN_REGISTRATION: Initial migration by passing addresses to constructor

contracts/Certification.sol, contracts/Committee.sol, contracts/ContractRegistry.sol, contracts/ContractRegistryAccessor.sol, contracts/Delegations.sol, contracts/Elections.sol, contracts/FeesWallet.sol, contracts/GuardiansRegistration.sol, contracts/IContractRegistryListener.sol, contracts/Lockable.sol, contracts/MonthlySubscriptionPlan.sol, contracts/Protocol.sol, contracts/Rewards.sol, contracts/StakingContractHandler.sol, contracts/Subscriptions.sol, contracts/spec_interfaces/IContractRegistry.sol, eth.ts, package.json, test/committee.spec.ts, test/contract-registry.spec.ts, test/delegations.spec.ts, test/driver.ts, test/fees-wallet.spec.ts, test/guardian-registration.spec.ts, test/helpers.ts, test/protocol-lockdown.spec.ts, test/staking-contract-handler.spec.ts, test/staking-rewards.spec.ts, typings/base-contract.d.ts, typings/contract-registry-contract.d.ts
- The registry keys are now a bytes32 id. Short names are encoded to bytes32 directly, longer names are hashed using `keccak256`
- Contracts are notified on registry changes.
=> CONTRACT_REGISTRY: Align to new set,get API, notify contracts on changes

contracts/Certification.sol, contracts/Committee.sol, contracts/ContractRegistry.sol, contracts/ContractRegistryAccessor.sol, contracts/Delegations.sol, contracts/Elections.sol, contracts/FeesWallet.sol, contracts/GuardiansRegistration.sol, contracts/IContractRegistryListener.sol, contracts/Lockable.sol, contracts/MonthlySubscriptionPlan.sol, contracts/Protocol.sol, contracts/Rewards.sol, contracts/StakingContractHandler.sol, contracts/Subscriptions.sol, contracts/spec_interfaces/IContractRegistry.sol, package.json, test/committee.spec.ts, test/contract-registry.spec.ts, test/delegations.spec.ts, test/driver.ts, test/fees-wallet.spec.ts, test/guardian-registration.spec.ts, test/helpers.ts, test/protocol-lockdown.spec.ts, test/staking-contract-handler.spec.ts, test/staking-rewards.spec.ts, typings/base-contract.d.ts, typings/contract-registry-contract.d.ts
All contracts that use `contractRegistryAccessor` now take the registry manager in the constructor and pass it on the the parent class.
=> CONTRACT_REGISTY_ACCESSOR: Pass registry manager in constructors 

contracts/Certification.sol, contracts/Committee.sol, contracts/ContractRegistry.sol, contracts/ContractRegistryAccessor.sol, contracts/Delegations.sol, contracts/Elections.sol, contracts/FeesWallet.sol, contracts/GuardiansRegistration.sol, contracts/Initializable.sol, contracts/Lockable.sol, contracts/ManagedContract.sol, contracts/MonthlySubscriptionPlan.sol, contracts/Protocol.sol, contracts/ProtocolWallet.sol, contracts/Rewards.sol, contracts/StakingContractHandler.sol, contracts/Subscriptions.sol, contracts/WithClaimableRegistryManagement.sol, contracts/for_testing/ManagedContractTest.sol, contracts/spec_interfaces/IContractRegistry.sol, contracts/spec_interfaces/ILockable.sol, test/contract-registry.spec.ts, test/driver.ts, test/initializable.spec.ts, test/matchers.ts, test/protocol-ownability.spec.ts, test/staking-contract-handler.spec.ts, typings/base-contract.d.ts, typings/contract-registry-contract.d.ts
Added the initializable pattern - the initialization manager has root access until initialization is complete
All managed contracts now inherit from a single contract - `ManagedContract`
=> Initializable, Managed Contract

contracts/Delegations.sol, test/elections.spec.ts
found discrepancy in how   `DelegatedStakeChanged` is being emitted in `emitDelegatedStakeChangedSlice`. compare with `emitDelegatedStakeChanged`
=> emit event with right parameters

contracts/Delegations.sol, contracts/spec_interfaces/IDelegation.sol, test/delegations.spec.ts, test/gas-scenarios.spec.ts, typings/delegations-contract.d.ts
implemented importDelegations with gas efficiency in mind:
1. changed method signature
1. new restrictions on initial state for import to succeed. delegators must be uninitialized.
Please notice - we could allow importing delegation for users with explicit self delegation. The current implementation requires that their delegation will be `0`, but the solution also holds for the case where their delegation is explicitly self delegation.
=> gas savings for importDelegations

contracts/Delegations.sol
A DelegatedStakeChanged event is not fired when a delegator with 0 stake is not longer self delegated
=> DELEGATIONS: bugfix

contracts/FeesWallet.sol, contracts/ProtocolWallet.sol
=> PROTOCOL_WALLET: safeMath, require startTime not in the past, block.timestamp instead of now

contracts/StakingRewards.sol, contracts/spec_interfaces/IStakingRewards.sol
=> STAKING_REWARDS: Change input types instead of casting (uint32, uint96)

contracts/FeesAndBootstrapRewards.sol, contracts/StakingRewards.sol, contracts/spec_interfaces/IFeesAndBootstrapRewards.sol, contracts/spec_interfaces/IStakingRewards.sol, test/rewards.spec.ts, typings/fees-and-bootstrap-rewards-contract.d.ts, typings/staking-rewards-contract.d.ts
- Added `withdrawnFees`, `withdrawenBootstrap`. Emitting `totalAwarded` in assignment events and `totalWithdrawn` in withdraw events.
- Adding `feesPerMember`, `bootstrapPerMember`, `certification` to assignment events
- Added `totalClaimed` and certification to `getFeesAndBootstrapData`
- Added `stake` to `delegatorStakingRewardsAssigned events`
=> REWARDS: add info to reward events, totalAwarded 

eth.ts
To easily load older versions of contracts
=> TESTKIT: getExisting to take an optional ABI override
